---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: openresty
  name: quotas-ns-pvc
  namespace: quotas-ns
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: nfs-client
