apiVersion: v2
name: grafana
description: Grafana
type: application
version: 6.50.6
appVersion: 9.3.6
dependencies:
  - name: grafana
    version: 6.50.6
    repository: https://grafana.github.io/helm-charts
