grafana:
  revisionHistoryLimit: 3
  testFramework:
    enabled: false
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      certmanager.k8s.io/cluster-issuer: monitoring-issuer
    hosts:
      - host: grafana.cluster.local
        paths:
        - path: /
          pathType: Prefix
    tls:
      - hosts:
        - grafana.cluster.local
        secretName: grafana-tls
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 128Mi
  persistence:
    type: pvc
    enabled: true
    storageClassName: nfs-client
    accessModes:
      - ReadWriteOnce
    size: 2Gi
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Victoria
        type: prometheus
        url: http://victoriametrics-victoria-metrics-single-server:8428
        access: proxy
        isDefault: true
