---
loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  compactor:
    retention_enabled: true
  limits_config:
    retention_period: 1d
  rulerConfig:
    storage:
      type: local
  auth_enabled: false

test:
  enabled: false

monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false

singleBinary:
  persistence:
    enabled: true
    size: 5Gi
    storageClass: nfs-client
  replicas: 1
