---
loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  compactor:
    retention_enabled: true
  limits_config:
    retention_period: 180d
rulerConfig:
  storage:
    type: local
singleBinary:
  persistence:
    enabled: true
    size: 30Gi
    storageClass: efs
  replicas: 1
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations: {}
    paths:
      write:
        - /api/prom/push
        - /loki/api/v1/push
      read:
        - /api/prom/tail
        - /loki/api/v1/tail
        - /loki/api
        - /api/prom/rules
        - /loki/api/v1/rules
        - /prometheus/api/v1/rules
        - /prometheus/api/v1/alerts
      singleBinary:
        - /api/prom/push
        - /loki/api/v1/push
        - /api/prom/tail
        - /loki/api/v1/tail
        - /loki/api
        - /api/prom/rules
        - /loki/api/v1/rules
        - /prometheus/api/v1/rules
        - /prometheus/api/v1/alerts

    hosts:
      - loki.cluster.local
