apiVersion: v2
name: nexporter
description: Install kube-state-metrics to generate and expose cluster-level metrics
type: application
version: 4.8.1
appVersion: 1.5.0
dependencies:
  - name: prometheus-node-exporter
    version: 4.8.1
    repository: https://prometheus-community.github.io/helm-charts