apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit
  labels:
    app: monitoring
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: monitoring/charts/fluentbit
    repoURL: 'https://github.com/optical4eye/kuber_plan'
    targetRevision: main
  project:  monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
