apiVersion: v1
entries:
  openresty-art:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2023-01-02T18:12:25.392620901+03:00"
    description: My openresty app
    digest: b68a3e4dc120e3bc6caa1cae2f21cff626f166fda016820d43930e94fab55227
    kubeVersion: '>= 1.19.0'
    name: openresty-art
    type: application
    urls:
    - https://raw.githubusercontent.com/optical4eye/kuber_plan/main/helm/chart/openresty-art-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2023-01-02T18:12:25.391869395+03:00"
    description: My openresty app
    digest: 3970afce6a0f8e40172cd6c76060fd28f296b225ec4c65608368f255e1eee6c4
    kubeVersion: '>= 1.19.0'
    name: openresty-art
    type: application
    urls:
    - https://raw.githubusercontent.com/optical4eye/kuber_plan/main/helm/chart/openresty-art-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2023-01-02T18:12:25.39118763+03:00"
    description: My openresty app
    digest: 3f0dc3ad535e3d84ccefdab330e788dcb9d4aeaab49d54aa1a44271f147fc1a3
    kubeVersion: '>= 1.19.0'
    name: openresty-art
    type: application
    urls:
    - https://raw.githubusercontent.com/optical4eye/kuber_plan/main/helm/chart/openresty-art-0.1.1.tgz
    version: 0.1.1
generated: "2023-01-02T18:12:25.390293875+03:00"
