victoria-metrics-single:
  rbac:
    create: false
    pspEnabled: false
  serviceAccount:
    create: false
  server:
    retentionPeriod: 6h
    extraArgs:
      selfScrapeInterval: "15s"
      loggerLevel: "INFO"
    persistentVolume:
      storageClass: "nfs-client"
      size: "10Gi"
    resources:
      requests:
        cpu: 200m
        memory: 500Mi
      limits:
        cpu: "1"
        memory: 2Gi
    # Indicates whether the Container is ready to service requests. If the readiness probe fails, the endpoints controller removes the Pod's IP address from the endpoints of all Services that match the Pod. The default state of readiness before the initial delay is Failure. If a Container does not provide a readiness probe, the default state is Success.
    readinessProbe:
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 5
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 3

    # Indicates whether the Container is running. If the liveness probe fails, the kubelet kills the Container, and the Container is subjected to its restart policy. If a Container does not provide a liveness probe, the default state is Success.
    livenessProbe: {}

    ingress:
      enabled: true
      annotations:
        certmanager.k8s.io/cluster-issuer: monitoring-issuer
      hosts:
        - name: "vm.cluster.local"
          path: /
          port: http
      tls:
        - secretName: "mon-tls"
          hosts:
            - vm.cluster.local
      ingressClassName: nginx
    statefulSet:
      enabled: true
      podManagementPolicy: Parallel
    scrape:
      enabled: false
