kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app-claim
  namespace: nfs-client
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi