---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: nfs-client
  labels:
    app: app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: openresty/openresty:centos-rpm
          imagePullPolicy: IfNotPresent
          env:
            - name: NGINX_HOST
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            limits:
              cpu: "0.2"
              memory: "300Mi"
            requests:
              cpu: "0.1"
              memory: "100Mi"
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            - name: pvc-sample
              mountPath: /var/log/nfs
      volumes:
        - name: pvc-sample
          persistentVolumeClaim:
            claimName: app-claim