---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: application
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: application
  serviceName: application-headless
  template:
    metadata:
      labels:
        app: application
    spec:
      initContainers:
        - name: init-configs
          image: busybox:1.36.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command:
            - 'sh'
            - '-c'
            - |
              sed -e "s/SERVER/$SERVER/" \
              /html-template/index.html | tee /html/index.html
              cp /html-template/50x.html /html/50x.html
          volumeMounts:
            - mountPath: /html-template
              name: html-template
            - mountPath: /html
              name: html
      containers:
        - name: application
          image: nginx:1.23
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html/
      volumes:
        - name: html-template
          configMap:
            name: nginx-template
  volumeClaimTemplates:
  - metadata:
      name: html
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: nfs-client
      resources:
        requests:
          storage: 10Mi