apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-application
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault.svc:8200"
    roleName: "application"
    objects: |
      - objectName: "get-application"
        secretPath: "secret/data/application"
        secretKey: "application"
      - objectName: "get-user"
        secretPath: "secret/data/application"
        secretKey: "user"
      - objectName: "get-password"
        secretPath: "secret/data/application"
        secretKey: "password"